# Generated by Django 5.1.7 on 2025-03-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('sexo', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('dataNascimento', models.DateField()),
                ('funcao', models.CharField(max_length=50)),
                ('telefone', models.IntegerField()),
            ],
        ),
    ]
