# Generated by Django 5.1.7 on 2025-03-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='insumo',
            field=models.ManyToManyField(blank=True, to='insumo.insumo'),
        ),
    ]
