# Generated by Django 5.1.7 on 2025-03-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_evento_insumo'),
        ('voluntario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='voluntario',
            field=models.ManyToManyField(blank=True, to='voluntario.voluntario'),
        ),
    ]
